### ISSUE TITLE
bug found in the inference: the rescaling of the gradient in the objective

### ISSUE THREAD

**Issue by CristianAntochi** [FlamTeam/flamedisx#36]
The line 425 in inference.py
`return ll, grad * self._guess_vect`
is not correct. 

The objective function is defined as 

     def objective(self, x_norm):
            x = x_norm * self._guess_vect
            params = dict(**self._fix)`

            for i, k in enumerate(self._varnames):
                params[k] = x[i]
            ll, grad = self.minus_ll(
                **params,
                autograph=self._autograph_objective,
                omit_grads=tuple(self._fix.keys()))

            if tf.math.is_nan(ll):
                tf.print(f"Objective at {tf.math.abs(x_norm)} is Nan!")
                ll *= float('inf')
                grad *= float('nan')
      return ll, grad * self._guess_vect

and as you can see,  the function is computed anyway in  x = x_norm * self._guess_vect and the gradient is already the correct one! The rescaling of the hessian and of the gradient is not necessary in the first place since the tape is anyway watching x and not x_norm.
The fix of it gets rid of the problem with the nan in the calculation of the errors of the fit parameters.

This will be fixed with the next PR.

**Comment by pelssers** [comment]
I agree that `minus_ll` returns the likelihood and gradients computed in the 'physical' space. But wasn't the argument that the optimizer works in the 'normalized' space and thus also needs normalized gradients and positions?
I remember we went back and forth on this a few times in the past so are we sure now, can we write a test for it?

> The fix of it gets rid of the problem with the nan in the calculation of the errors of the fit parameters.

Do you mean from `bestfit` or `inverse_hessian`? because only `bestfit` uses `objective`.

**Comment by CristianAntochi** [comment]
So, the optimiser optimises the x_norm, but it computes the true gradient in x = x_norm * guess, with the tape watching x and not x norm. So we should either take away the x_norm or watch x_norm and not x in the gradient. 

The nan-s come from the summary witch calls `inverse_hessian`. This means the gradient computed is wrong in the fitting and is different than the recomputation of it in the `inverse_hessian`. This means the values of convergence are actually not really converged according to the true gradient, since the gradient of the objective is the one evaluated in the best_fit. This means the hessian is not positive defined and there are negative values on the diagonal of the covariance matrix, hence the nan-s.

**Comment by JelleAalbers** [comment]
Our reasoning was that the optimizer works on x_norm = x / guess, so it must get the gradient d/dx_norm = guess * d/dx. The tape gives d/dx, so we need to multiply by guess before passing the gradient to the optimizer.

But it's clear something is going wrong since we got NaNs before, but you don't see them when you remove the objective scaling. I am still puzzled.

**Comment by CristianAntochi** [comment]
The optimiser does work on x_norm in the objective, but not in the objective gradient, and this can be clearly seen here:

        for i, k in enumerate(self._varnames):
            params[k] = x[i]
        ll, grad = self.minus_ll(
            **params,
            autograph=self._autograph_objective,
            omit_grads=tuple(self._fix.keys())

What I assume the optimiser does is just changing the value of x_norm and for the same x_norm it checks the computed gradient at x (as defined in the objective function) and does not compute the gradient itself of the function in x_norm. 
This somehow makes sense to me, otherwise why would it need the gradient in the first place since it should find the 0s of the gradient to minimise...

**Comment by pelssers** [comment]
> So, the optimiser optimises the x_norm, but it computes the true gradient in x = x_norm * guess, with the tape watching x and not x norm. So we should either take away the x_norm or watch x_norm and not x in the gradient.

`minus_ll` computes the true likelihood and gradient which is what we want and should not change.

As I understand it the optimizer just repeatedly calls `objective` with the scaled/normalized positions and so `objective` should return the scaled/normalized gradients. Converting from the true gradients to the scaled ones is done right before `objective` returns. But how exactly the conversion is done might be wrong.

>  This means the gradient computed is wrong in the fitting and is different than the recomputation of it in the `inverse_hessian`. 

So you're saying that `inverse_hessian` gives nans because `bestfit` doesn't actually return the best fit position (because of incorrectly scaled gradients).

Can we come up with a test to figure this out:
How about we have a simple one parameter likelihood which we can scan by calling `LogLikelihood` repeatedly to get the likelihood curve. Then compare to where bestfit thinks the minimum is. Secondly we can compute the gradient away from the minimum and see if its the same as what we see from the curve.

**Comment by CristianAntochi** [comment]
I will try to do that.
After talking to @JelleAalbers , since it seems that the optimiser works without problems without any x_norm, I will take it out, avoiding possible errors with the scaling.

**Comment by pelssers** [comment]
If taking out `x_norm` works, that would be the cleanest solution. I guess we always assumed the optimizer can't handle parameters with very different scales but never tested it.

**Comment by CristianAntochi** [comment]
> How about we have a simple one parameter likelihood which we can scan by calling `LogLikelihood` repeatedly to get the likelihood curve. Then compare to where bestfit thinks the minimum is. Secondly we can compute the gradient away from the minimum and see if its the same as what we see from the curve.

With one parameter is hard to get nan-s in the covariance matrix... I will do it with 2 or 3.
