### ISSUE TITLE
ColumnSource simulator

### ISSUE THREAD

**Issue by pelssers** [FlamTeam/flamedisx#47]
@CristianAntochi just pointed out that ColumnSource has no `simulate` method. How would we implement one given that the differential rate of events in a ColumnSource are precomputed and passed in via data.

**Comment by pelssers** [comment]
As @JelleAalbers said out during the review of #51 we could do this in the meantime:
>For columnsource perhaps we can add a default simulate that returns no events and emits a warning to tell the user they should provide the method?

**Comment by pelssers** [comment]
Implemented @JelleAalbers suggestion in #54. SourceBase now has an 'abstract' simulate method. A test is added.

**Comment by JelleAalbers** [comment]
Closing, since a generic ColumnSource simulate method is not meaningful / not defined. Users should provide this if using a ColumnSource. You added the warning, that's the best we can do.

We could someday add more advanced ColumnSource-like things, e.g. HistogramSource, which would have a simulate method.
